discount: 0.10
excluded_countries:
  - Syria
  - Mauritania
  - Iraq
  - Socotra
  - Venezuela
  - Russian Caucasus
  - Arctic Russia
  - Somaliland
  - Yemen
  - Kazakhstan
  - Eritrea
countries:
  - Eritrea
  - Mauritania
  - Libya
  - Iraq
  - Syria
  - Turkmenistan
  - Pakistan
  - Kazakhstan
  - Venezuela
  - Russian Caucasus
  - Arctic Russia
  - Yemen
  - Somaliland
  - Socotra
  - Eritrea + Somaliland
  - Yemen + Socotra
  - North Korea
  - Afghanistan
  - South Sudan
  - Central African Republic
  - Chad
  - Niger
  - Mali
  - Burkina Faso
  - Guinea-Bissau
  - Comoros
  - South Ossetia
  - Abkhazia
  - Transnistria
  - Nagorno-Karabakh
  - Western Sahara
  - South Sudan + Sudan
  - Mali + Burkina Faso
  - East Timor
  - Papua New Guinea
  - Solomon Islands
  - Vanuatu
  - Kiribati
  - Tuvalu
  - Nauru
  - Marshall Islands
  - Federated States of Micronesia
  - Palau
  - Northern Mariana Islands
  - Guam
  - American Samoa
  - Cook Islands
  - Niue
  - Tokelau
  - Pitcairn Islands
  - Easter Island
  - Galapagos Islands
  - Falkland Islands
  - South Georgia and South Sandwich Islands
  - Bouvet Island
  - Heard Island and McDonald Islands
  - French Southern Territories
  - Svalbard and Jan Mayen
  - Faroe Islands
  - Greenland
  - Saint Helena
  - Ascension Island
  - Tristan da Cunha
  - Mayotte
  - Réunion
  - French Guiana
  - Suriname
  - Guyana
  - Belize
  - El Salvador
  - Honduras
  - Nicaragua
  - Guatemala
  - Haiti
  - Dominican Republic
  - Cuba
  - Jamaica
  - Bahamas
  - Turks and Caicos Islands
  - Cayman Islands
  - British Virgin Islands
  - US Virgin Islands
  - Anguilla
  - Saint Martin
  - Saint Barthélemy
  - Guadeloupe
  - Martinique
  - Dominica
  - Saint Lucia
  - Saint Vincent and the Grenadines
  - Grenada
  - Barbados
  - Trinidad and Tobago
  - Aruba
  - Curaçao
  - Bonaire
  - Sint Maarten
  - Sint Eustatius
  - Saba
  - Montserrat
  - Antigua and Barbuda
  - Saint Kitts and Nevis
  - Seychelles
  - Mauritius
  - Maldives
  - Sri Lanka
  - Bangladesh
  - Myanmar
  - Laos
  - Cambodia
  - Vietnam
  - Philippines
  - Indonesia
  - Malaysia
  - Brunei
  - Singapore
  - East Timor
  - Papua New Guinea
  - Solomon Islands
  - Vanuatu
  - Kiribati
  - Tuvalu
  - Nauru
  - Marshall Islands
  - Federated States of Micronesia
  - Palau
  - Northern Mariana Islands
  - Guam
  - American Samoa
  - Cook Islands
  - Niue
  - Tokelau
  - Pitcairn Islands
  - Easter Island
  - Galapagos Islands
  - Falkland Islands
  - South Georgia and South Sandwich Islands
  - Bouvet Island
  - Heard Island and McDonald Islands
  - French Southern Territories
  - Svalbard and Jan Mayen
  - Faroe Islands
  - Greenland
  - Saint Helena
  - Ascension Island
  - Tristan da Cunha
  - Mayotte
  - Réunion
  - French Guiana
  - Suriname
  - Guyana
  - Belize
  - El Salvador
  - Honduras
  - Nicaragua
  - Guatemala
  - Haiti
  - Dominican Republic
  - Cuba
  - Jamaica
  - Bahamas
  - Turks and Caicos Islands
  - Cayman Islands
  - British Virgin Islands
  - US Virgin Islands
  - Anguilla
  - Saint Martin
  - Saint Barthélemy
  - Guadeloupe
  - Martinique
  - Dominica
  - Saint Lucia
  - Saint Vincent and the Grenadines
  - Grenada
  - Barbados
  - Trinidad and Tobago
  - Aruba
  - Curaçao
  - Bonaire
  - Sint Maarten
  - Sint Eustatius
  - Saba
  - Montserrat
  - Antigua and Barbuda
  - Saint Kitts and Nevis
  - Seychelles
  - Mauritius
  - Maldives
  - Sri Lanka
  - Bangladesh
  - Myanmar
  - Laos
  - Cambodia
  - Vietnam
  - Philippines
  - Indonesia
  - Malaysia
  - Brunei
  - Singapore
 